// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/TwitchChat/TwitchChat.proto

package go_micro_service_TwitchChat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TwitchChat service

type TwitchChatService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TwitchChat_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (TwitchChat_PingPongService, error)
}

type twitchChatService struct {
	c    client.Client
	name string
}

func NewTwitchChatService(name string, c client.Client) TwitchChatService {
	return &twitchChatService{
		c:    c,
		name: name,
	}
}

func (c *twitchChatService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "TwitchChat.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *twitchChatService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (TwitchChat_StreamService, error) {
	req := c.c.NewRequest(c.name, "TwitchChat.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &twitchChatServiceStream{stream}, nil
}

type TwitchChat_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type twitchChatServiceStream struct {
	stream client.Stream
}

func (x *twitchChatServiceStream) Close() error {
	return x.stream.Close()
}

func (x *twitchChatServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twitchChatServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twitchChatServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twitchChatServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *twitchChatService) PingPong(ctx context.Context, opts ...client.CallOption) (TwitchChat_PingPongService, error) {
	req := c.c.NewRequest(c.name, "TwitchChat.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &twitchChatServicePingPong{stream}, nil
}

type TwitchChat_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type twitchChatServicePingPong struct {
	stream client.Stream
}

func (x *twitchChatServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *twitchChatServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *twitchChatServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twitchChatServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twitchChatServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *twitchChatServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TwitchChat service

type TwitchChatHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, TwitchChat_StreamStream) error
	PingPong(context.Context, TwitchChat_PingPongStream) error
}

func RegisterTwitchChatHandler(s server.Server, hdlr TwitchChatHandler, opts ...server.HandlerOption) error {
	type twitchChat interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type TwitchChat struct {
		twitchChat
	}
	h := &twitchChatHandler{hdlr}
	return s.Handle(s.NewHandler(&TwitchChat{h}, opts...))
}

type twitchChatHandler struct {
	TwitchChatHandler
}

func (h *twitchChatHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.TwitchChatHandler.Call(ctx, in, out)
}

func (h *twitchChatHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.TwitchChatHandler.Stream(ctx, m, &twitchChatStreamStream{stream})
}

type TwitchChat_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type twitchChatStreamStream struct {
	stream server.Stream
}

func (x *twitchChatStreamStream) Close() error {
	return x.stream.Close()
}

func (x *twitchChatStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twitchChatStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twitchChatStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twitchChatStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *twitchChatHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.TwitchChatHandler.PingPong(ctx, &twitchChatPingPongStream{stream})
}

type TwitchChat_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type twitchChatPingPongStream struct {
	stream server.Stream
}

func (x *twitchChatPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *twitchChatPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *twitchChatPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *twitchChatPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *twitchChatPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *twitchChatPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
